#!/bin/bash
clear

## Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

## Date
### mm/dd/yyyy ####
now="$(date +'%d.%m.%Y')"

echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
echo -e $YELLOW"# Created by h3x at SolidOptionOS. All rights reserved 2015     #"$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
cd ~/
pwd
echo ""
sleep 0.5
echo -e $YELLOW"Checking for root access.. "$ENDCOLOR
sleep 0.5
if [ $USER != root ]; then
echo -e $RED"[h3x]:Error: must be root"$ENDCOLOR
echo -e $BLUE"[h3x]:Exiting..."$ENDCOLOR
exit 0
fi
sleep 1
echo -e $YELLOW"Plese enter the path where the SolidOptionOS scripts are: [ex '/root/optionZ3ro/scripts'] "
read soospath
echo -e $BLUE"Thank you."$ENDCOLOR
sleep 1
cd $soospath
pwd
sleep 1
echo -e $BLUE"Let's start with copying our files to /tmp/scripts"$ENDCOLOR
sleep 0.5
mkdir /tmp/scripts
cp * /tmp/scripts
cd /tmp/scripts
pwd
ls -al 
sleep 1 
echo -e $BLUE"Renaming all files."$ENDCOLOR
sleep 0.5
for file in *.sh
do
    mv -i "${file}" "${file/.sh/ }"
done
sleep 1
echo -e $BLUE"Escalating permissions of all files to 'executable'."$ENDCOLOR
sleep 0.5
chmod +x *
ls -al
echo -e $BLUE"Ok, now we are ready to move them."$ENDCOLOR
sleep 1
echo -e $YELLOW"Would you like to add all of the scripts to: '/usr/local/bin'. "$ENDCOLOR;
read addtobin
if [[ $addtobin = y || $addtobin = Y]] ; then
echo -e $BLUE"Ok. Adding all scripts to '/usr/local/bin'.."$ENDCOLOR 
sleep 1
cp /tmp/scripts/* /usr/local/bin
cp /tmp/scripts/* /usr/local/sbin
cp /tmp/scripts/* /usr/bin
cp /tmp/scripts/* /usr/sbin
cp /tmp/scripts/* /bin
cp /tmp/scripts/* /sbin
echo -e $YELLOW"Done."$ENDCOLOR
exit 0

else

echo -e $YELLOW"Ok. Maybe some other time."$ENDCOLOR
exit 0
fi
