#!/bin/bash
#
# title: git-setup
# author:  Christopher Earnhart 
# author_email: chris@christopherearnhart.com
# author_website: http://christopherearnhart.com
#
# color vars
RED="\033[1;31m"
GREEN="\033[2;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"
# end color vars

# browser vars
BROWSER=firefox
# end browser vars

# git vars
gitPersonalAccessToken=https://github.com/settings/tokens
gitSSHKeys=https://github.com/settings/keys
gitCredPath=$HOME
gitCredFile='git.store'
# end git vars
clear
echo -e $BLUE"#################################################################"$ENDCOLOR; 
echo -e $YELLOW"   ____     ___    __  ____       __  _             ____  ____"$ENDCOLOR;
echo -e $YELLOW"  / __/__  / (_)__/ / / __ \___  / /_(_)__  ___    / __ \/ __/"$ENDCOLOR;
echo -e $YELLOW" _\ \/ _ \/ / / _  / / /_/ / _ \/ __/ / _ \/ _ \  / /_/ /\ \  "$ENDCOLOR;
echo -e $YELLOW"/___/\___/_/_/\_,_/  \____/ .__/\__/_/\___/_//_/  \____/___/  "$ENDCOLOR;
echo -e $YELLOW"                         /_/                                  "$ENDCOLOR;
echo -e $BLUE"#################################################################"$ENDCOLOR;
echo ""

echo -e $YELLOW"Let's setup your github config"$ENDCOLOR;
echo ""

echo -e $YELLOW"Enter your github username: "$ENDCOLOR;
read githubusername
echo ""

echo -e $BLUE"Registering global user.name.."$ENDCOLOR;
git config --global user.name $githubusername
echo ""

echo -e $YELLOW"Enter your github email address: "$ENDCOLOR;
read githubemailaddress
echo ""

echo -e $BLUE"Registering global email.address.."$ENDCOLOR;
git config --global user.email $githubemailaddress
echo ""

echo -e $YELLOW"Would you like to create a credentials file for git? [Y/n] "$ENDCOLOR;
read createGitCreds

if [[ $createGitCreds = 'y' || $createGitCreds = 'Y' ]]; then

  echo ""
  echo -e $BLUE"Creating '$gitCredFile in $gitCredPath'.."$ENDCOLOR;
  echo ""

  echo -e $YELLOW"Enter your github host: [e.g. github.com/solidOptionOS] "$ENDCOLOR;
  read mygithost
  echo ""

  gitCredUsername=$githubusername

  echo -e $YELLOW"Enter your github password: "$ENDCOLOR;
  read gitCredPass
  echo ""
  
  echo -e $BLUE"Creating $gitCredFile with username $gitCredUsername and password $gitCredPass to be stored in $gitCredPath.."$ENDCOLOR;
  echo ""
  
  echo -e "git config --global credential.helper 'store --file "$gitCredPath/$gitCredFile"'"
  
  echo -e 'git credential-store --file '"$gitCredPath"'/'"$gitCredFile"' store\n'
  echo -e 'protocol=https \nhost='"$mygithost"' \nusername='"$gitCredUsername"' \npassword='"$gitCredPass"' \n\n' 

  echo ""
  echo -e $BLUE"Checking credentials.."$ENDCOLOR;
  echo -e 'git credential-store --file '"$HOME"'/'"$gitCredFile"' get\n'
  echo -e '\n'
  
  echo -e $BLUE"Your github credentials are stored."$ENDCOLOR;
  echo ""

else

  echo ""
  echo -e $YELLOW"Okay. Maybe later."$ENDCOLOR;
  echo ""

fi
  
echo -e $BLUE"Select push.default ['simple' or 'matching']"$ENDCOLOR;
read defaultpush
echo ""

echo -e $YELLOW"Registering push.default $defaultpush."$ENDCOLOR;
git config --global push.default $defaultpush
echo ""

echo -e $YELLOW"Checking for SSH keys.."$ENDCOLOR;
echo ""
ls -al ~/.ssh
echo ""

echo -e $BLUE"Generating a public/private rsa key pair.."$ENDCOLOR;
echo ""
ssh-keygen -t rsa -b 4096 -C "$githubemailaddress"
echo "" 

echo -e $BLUE"Starting ssh-agent"$ENDCOLOR;
echo ""
sleep 1
eval "$(ssh-agent -s)"
echo ""

echo -e $BLUE"Adding new SSH key to the ssh-agent"$ENDCOLOR;
echo ""
ssh-add ~/.ssh/id_rsa
echo ""

echo -e $BLUE"New key created."$ENDCOLOR;
echo ""
cat ~/.ssh/id_rsa.pub
echo ""

echo -e $YELLOW"Copying to clipboard.."$ENDCOLOR;
cat ~/.ssh/id_rsa.pub | xclip -selection clipboard       

echo ""

#echo -e $YELLOW "Using $gitCredFile to login to github.." $ENDCOLOR;
#echo ""

echo -e $YELLOW "When github appears in the browser, ADD A NEW SSH KEY, name it, and paste the contents of the clipboard into the key text-area." $ENDCOLOR;
echo ""
 
$BROWSER $gitSSHKeys > /dev/null 2>&1 &

echo -e $YELLOW "When you have added the key, enter 'done' here: " $ENDCOLOR;
read readytogo

if [[ $readytogo = 'done' ]] ; then

  echo ""
  echo -e $BLUE "Okay, let us test the connection." $ENDCOLOR;
  echo ""
  sleep 1
  
  ssh -vT $githubusername@github.com
  echo ""

fi

echo -e $BLUE "If you have authenticated, and the username in the message is yours,  then you have successfully set up your SSH Key!" $ENDCOLOR;
echo ""
sleep 1

echo -e $YELLOW "Fail to authenticate? [y/N] " $ENDCOLOR;
read problemorsuccess

if [[ $problemorsuccess = 'y' || $problemorsuccess = 'Y' ]]; then

  echo ""
  echo -e $BLUE "No problem.  Let us try a different method." $ENDCOLOR;
  echo "" 
  
  echo -e $YELLOW "We are going to create a personal access token." $ENDCOLOR;
  echo ""

  $BROWSER '$gitPersonalAccessToken' > /dev/null 2>&1 & 
  
  echo -e $YELLOW "When you have generated the token, enter it here: " $ENDCOLOR;
  read privategithubtoken
  echo ""
  
  echo -e $BLUE "Got it. Importing the token." $ENDCOLOR;
  echo ""
  
  curl -u $githubusername:$privategithubtoken https://api.github.com/user
  echo ""

fi

echo ""
echo -e $YELLOW "SUCCESS! You are now setup and ready to start using git!" $ENDCOLOR;
